services:
  - type: web
    name: tikapi
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TIKAPI_KEY
        sync: false
